name: Extended Folder Replicator

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
        shell: bash

      - name: Install package dependencies
        run: |
          pip install -r requirements.txt
          # Debug: Show content of pyproject.toml and setup files
          echo "=== pyproject.toml ==="
          cat pyproject.toml || echo "No pyproject.toml found"
          echo "=== setup.py ==="
          cat setup.py || echo "No setup.py found"
          echo "=== setup.cfg ==="
          cat setup.cfg || echo "No setup.cfg found"
          # Try to generate egg info anyway
          python setup.py egg_info || echo "Warning: egg_info failed, continuing anyway"
        shell: bash

      - name: Install package
        run: |
          # Try installation methods in order of preference
          echo "Attempting installation methods..."

          echo "1. Try pip install -e ."
          pip install -e . && exit 0 || echo "Method 1 failed"

          echo "2. Try pip install ."
          pip install . && exit 0 || echo "Method 2 failed"

          echo "3. Try setup.py develop"
          python setup.py develop && exit 0 || echo "Method 3 failed"

          echo "4. Try setup.py install"
          python setup.py install && exit 0 || echo "Method 4 failed"

          echo "All installation methods failed"
          exit 1
        shell: bash

      - name: Verify and test core commands
        run: |
          # Basic setup
          mkdir -p source dest
          echo "test file" > source/test.txt

          # Test core commands
          frep config show || (echo "Failed to show config" && exit 1)
          frep add source dest || (echo "Failed to add directory" && exit 1)
          frep list || (echo "Failed to list replications" && exit 1)
          frep sync || (echo "Failed to sync" && exit 1)
          frep status || (echo "Failed to show status" && exit 1)

          # Quick watch test
          timeout 5s frep watch --interval 1 &
          WATCH_PID=$!
          sleep 2
          kill $WATCH_PID 2>/dev/null || true
        shell: bash
