name: Extended Folder Replicator

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create README.md
        run: |
          echo "# Extended Folder Replicator" > README.md
          echo "" >> README.md
          echo "A CLI-based folder replication and synchronization tool." >> README.md
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Set up test folders
        run: |
          mkdir -p test_src test_dest
          echo "Hello, world!" > test_src/testfile.txt
        shell: bash

      # Step to add source and destination folders
      - name: Add folders to frep
        run: |
          frep add test_src test_dest
        shell: bash

      - name: Run `frep sync`
        run: |
          frep sync 

      - name: Validate file replication
        run: |
          if [ ! -f "test_dest/testfile.txt" ]; then
            echo "Error: File not copied!"
            exit 1
          fi
        shell: bash

