name: Extended Folder Replicator

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Test configuration commands
        run: |
          frep config show
          frep config set sync_interval 30
          frep config set log_level DEBUG
          frep config set max_log_size 20
          frep config show | grep -q "sync_interval: 30" || exit 1
          frep config show | grep -q "log_level: DEBUG" || exit 1
          frep config show | grep -q "max_log_size: 20" || exit 1
        shell: bash

      - name: Set up test environment
        run: |
          mkdir -p test_src/subdir test_dest
          mkdir -p test_src2 test_dest2
          echo "Hello, world!" > test_src/testfile.txt
          echo "Test content" > test_src/subdir/subfile.txt
          echo "temp file" > test_src/temp.tmp
          echo "log file" > test_src/test.log
          echo "Second source" > test_src2/file2.txt
        shell: bash

      - name: Test add command
        run: |
          frep add test_src test_dest
          frep add test_src2 test_dest2 --exclude "*.tmp" "*.log"
          frep list | grep -q "test_src -> test_dest" || exit 1
          frep list | grep -q "test_src2 -> test_dest2" || exit 1
        shell: bash

      - name: Test sync command
        run: |
          frep sync
          test -f "test_dest/testfile.txt" || exit 1
          test -f "test_dest/subdir/subfile.txt" || exit 1
          test -f "test_dest2/file2.txt" || exit 1
          test ! -f "test_dest2/temp.tmp" || exit 1
          test ! -f "test_dest2/test.log" || exit 1
        shell: bash

      - name: Test status command
        run: |
          frep status
          frep status test_src | grep -q "Source files:" || exit 1
          frep status test_src | grep -q "Source files: 4" || exit 1
          frep status test_src2 | grep -q "Source files: 1" || exit 1
        shell: bash

      - name: Test watch command
        run: |
          timeout 30s frep watch --interval 1 &
          WATCH_PID=$!
          sleep 5
          echo "New file" > test_src/newfile.txt
          sleep 5
          test -f "test_dest/newfile.txt" || exit 1
          kill $WATCH_PID || true
        shell: bash

      - name: Test remove command
        run: |
          frep remove test_src2 --force
          ! frep list | grep -q "test_src2" || exit 1
          echo "Final test" > test_src/finaltest.txt
          frep sync
          test -f "test_dest/finaltest.txt" || exit 1
        shell: bash

      - name: Test log commands
        run: |
          frep logs --tail 10
          frep logs --clear --force
          ! test -s "$(find ~/.local/share/FolderReplicator/logs -type f -name "*.log")" || exit 1
        shell: bash
