name: Extended Folder Replicator

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Test configuration commands
        run: |
          frep config show || (echo "Failed to show initial config" && exit 1)

          frep config set sync_interval 30 || (echo "Failed to set sync_interval" && exit 1)
          frep config set log_level DEBUG || (echo "Failed to set log_level" && exit 1)
          frep config set max_log_size 20 || (echo "Failed to set max_log_size" && exit 1)

          CONFIG_OUTPUT=$(frep config show)
          echo "$CONFIG_OUTPUT" | grep -E "Sync interval: *30" || (echo "sync_interval value mismatch" && exit 1)
          echo "$CONFIG_OUTPUT" | grep -E "Log level: *DEBUG" || (echo "log_level value mismatch" && exit 1)
          echo "$CONFIG_OUTPUT" | grep -E "Max log size: *20(\.0)? MB" || (echo "max_log_size value mismatch" && exit 1)
        shell: bash

      - name: Set up test environment
        run: |
          mkdir -p test_src/subdir test_dest
          mkdir -p test_src2 test_dest2

          echo "Hello, world!" > test_src/testfile.txt
          echo "Test content" > test_src/subdir/subfile.txt
          echo "temp file" > test_src/temp.tmp
          echo "log file" > test_src/test.log
          echo "Second source" > test_src2/file2.txt

          [[ -f test_src/testfile.txt && -f test_src/subdir/subfile.txt && -f test_src/temp.tmp && -f test_src/test.log && -f test_src2/file2.txt ]] || (echo "Failed to create test files" && exit 1)
        shell: bash

      - name: Test add command
        run: |
          frep add test_src test_dest || (echo "Failed to add first replication" && exit 1)
          frep add test_src2 test_dest2 --exclude "*.tmp" "*.log" || (echo "Failed to add second replication" && exit 1)

          LIST_OUTPUT=$(frep list)
          echo "$LIST_OUTPUT" | grep -E "test_src.*->.*test_dest" || (echo "First replication not found in list" && exit 1)
          echo "$LIST_OUTPUT" | grep -E "test_src2.*->.*test_dest2" || (echo "Second replication not found in list" && exit 1)
        shell: bash

      - name: Test sync command
        run: |
          frep sync || (echo "Sync command failed" && exit 1)

          [[ -f "test_dest/testfile.txt" ]] || (echo "Missing testfile.txt in destination" && exit 1)
          [[ -f "test_dest/subdir/subfile.txt" ]] || (echo "Missing subfile.txt in destination" && exit 1)
          [[ -f "test_dest2/file2.txt" ]] || (echo "Missing file2.txt in destination 2" && exit 1)
          [[ ! -f "test_dest2/temp.tmp" ]] || (echo "Excluded temp.tmp file found" && exit 1)
          [[ ! -f "test_dest2/test.log" ]] || (echo "Excluded test.log file found" && exit 1)
        shell: bash

      - name: Test status command
        run: |
          # Run status command and capture output
          STATUS_OUTPUT=$(frep status 2>&1) || {
            echo "Status command failed:"
            echo "$STATUS_OUTPUT"
            exit 1
          }

          echo "$STATUS_OUTPUT"

          # Validate test_src sync (4/4)
          echo "$STATUS_OUTPUT" | grep -q "test_src.*->.*" && 
          echo "$STATUS_OUTPUT" | grep -q "Files synced:.*4/4" || {
            echo "❌ test_src did not sync 4/4 files as expected."
            exit 1
          }

          # Validate test_src2 sync (1/1)
          echo "$STATUS_OUTPUT" | grep -q "test_src2.*->.*" && 
          echo "$STATUS_OUTPUT" | grep -q "Files synced:.*1/1" || {
            echo "❌ test_src2 did not sync 1/1 file as expected."
            exit 1
          }

          echo "✅ Replication status checks passed."
        shell: bash

      - name: Test watch command
        run: |
          timeout 30s frep watch --interval 1 &
          WATCH_PID=$!

          sleep 2
          echo "New file" > test_src/newfile.txt

          for i in $(seq 1 10); do
            if [[ -f "test_dest/newfile.txt" ]]; then
              break
            fi
            sleep 2
            if [[ $i -eq 10 ]]; then
              echo "Watch mode failed to sync new file"
              exit 1
            fi
          done

          kill $WATCH_PID 2>/dev/null || true
        shell: bash

      - name: Test remove command
        run: |
          frep remove test_src2 --force || (echo "Remove command failed" && exit 1)
          frep list | grep -q "test_src2" && (echo "Replication still exists after removal" && exit 1)

          echo "Final test" > test_src/finaltest.txt
          frep sync || (echo "Final sync failed" && exit 1)
          [[ -f "test_dest/finaltest.txt" ]] || (echo "Final test file not synced" && exit 1)
        shell: bash

      - name: Test log commands
        run: |
          frep logs --tail 10 || (echo "Failed to view logs" && exit 1)
          frep logs --clear --force || (echo "Failed to clear logs" && exit 1)

          LOG_FILES=$(find ~/.local/share/FolderReplicator/logs -type f -name "*.log" 2>/dev/null || find "$LOCALAPPDATA/FolderReplicator/Logs" -type f -name "*.log" 2>/dev/null || true)
          [[ -z "$LOG_FILES" ]] || (echo "Log files still exist after clear" && exit 1)
        shell: bash
